name: ci
on:
  push:
     branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
        #setup Nodejs Environment
      - name: setup Nodejs
        uses: actions/setup-node@v4.1.0
        
        #Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          
        #setup docker compose
      - name: setup docker
        uses: docker/setup-compose-action@v1.0.0

        #run docker compose
      - name: run docker compose
        run: docker-compose up -d

        # Install AWS CLI
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      # Verify AWS CLI installation
      - name: Verify AWS CLI
        run: aws --version

      # Configure AWS credentials
      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.awsaccesskeyid }}
          aws configure set aws_secret_access_key ${{ secrets.awssecretaccesskey }}
          aws configure set default.region ${{ secrets.region }}

        # Docker Authorization with AWS ECR
      - name: Docker login to aws ecr
        run: aws ecr get-login-password --region ${{ secrets.region }} | docker login --username AWS --password-stdin  ${{ secrets.awsaccountid }}.dkr.ecr.${{ secrets.region }}.amazonaws.com

        # Tag frontend and backend images
      - name: Tag frontend and backend
        run: |
          docker tag  mern-app-node-app ${{ secrets.awsaccountid }}.dkr.ecr.${{ secrets.region }}.amazonaws.com/basicmernapp:tag 
          docker tag  mern-app-react-app ${{ secrets.awsaccountid }}.dkr.ecr.${{ secrets.region }}.amazonaws.com/basicmernapp:tag
        
        # Push Tagged Image
      - name: Push Tagged image
        run: |
           docker push ${{ secrets.awsaccountid }}.dkr.ecr.${{ secrets.region }}.amazonaws.com/basicmernapp:tag

        
