name: CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
        
      # Setup Node.js Environment
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 16 # Specify the Node.js version as needed
      
      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version # Verify installation
      
      # Optional: Setup Docker Buildx for Multi-Platform Support
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Run Docker Compose to Build and Run Containers
      - name: Build and Start Containers
        run: docker-compose up -d
        
      # Install AWS CLI
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version # Verify AWS CLI installation
          
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.awsaccesskeyid }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.awssecretaccesskey }}
          AWS_DEFAULT_REGION: ${{ secrets.region }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION
      
      # Docker Login to AWS ECR
      - name: Docker Login to AWS ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 677276090090.dkr.ecr.ap-south-1.amazonaws.com
      
      # Tag Frontend and Backend Docker Images
      - name: Tag Docker Images
        run: |
          docker tag mern-app-node-app ${{ secrets.awsaccountid }}.dkr.ecr.${{ secrets.region }}.amazonaws.com/basicmernapp-node:latest
          docker tag mern-app-react-app ${{ secrets.awsaccountid }}.dkr.ecr.${{ secrets.region }}.amazonaws.com/basicmernapp-react:latest
      
      # Push Tagged Docker Images to ECR
      - name: Push Docker Images
        run: |
          docker push ${{ secrets.awsaccountid }}.dkr.ecr.${{ secrets.region }}.amazonaws.com/basicmernapp-node:latest
          docker push ${{ secrets.awsaccountid }}.dkr.ecr.${{ secrets.region }}.amazonaws.com/basicmernapp-react:latest
