on:
  push:
     branches:
          - main
env:
  ECR_REPOSITORY: basicmernapp
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # checkout code
      - name: code checkout
        uses: actions/checkout@v4.2.2

      - name: AWS cli install action
  # You may pin to the exact commit or the version.
  # uses: chrislennon/action-aws-cli@1347f1da2852be38fdbea5e6e336f1e297fec7a0
        uses: chrislennon/action-aws-cli@1.1
          
        # aws credentials 
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: ap-south-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: ecr dockr login , Build, tag, and push image to Amazon ECR
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: | 
         aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 677276090090.dkr.ecr.ap-south-1.amazonaws.com
         cd client
         docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
         docker push 677276090090.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_TAG
         echo "image=$ECR_REGISTRY:$IMAGE_TAG" >> $GITHUB_OUTPUT
