name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: public.ecr.aws/m7y5i5k9
  CLIENT_REPOSITORY: employeeapp
  SERVER_REPOSITORY: employeeapp
  aws_account_id

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Login to Amazon ECR
      - name: Login to Amazon ECR
        run: |
             aws ecr get-login-password --region AWS_REGION | docker login --username AWS --password-stdin 677276090090.dkr.ecr.AWS_REGION.amazonaws.com

      # Step 4: Build and Push Client Image
      - name: Build and Push Client Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: | 
          echo "Building Client Docker image..."
          docker build -t $ECR_REGISTRY/$CLIENT_REPOSITORY:$IMAGE_TAG ./client

          echo "Pushing Client Docker image..."
          docker push $ECR_REGISTRY/$CLIENT_REPOSITORY:$IMAGE_TAG

      # Step 5: Build and Push Server Image
      - name: Build and Push Server Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: | 
          echo "Building Server Docker image..."
          docker build -t $ECR_REGISTRY/$SERVER_REPOSITORY:$IMAGE_TAG ./server

          echo "Pushing Server Docker image..."
          docker push $ECR_REGISTRY/$SERVER_REPOSITORY:$IMAGE_TAG
