name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: public.ecr.aws/m7y5i5k9
  CLIENT_REPOSITORY: employeeapp-client
  SERVER_REPOSITORY: employeeapp-server
  AWS_ACCOUNT_ID: 677276090090

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: ${{ env.AWS_REGION }}

          
      - name: Build and Push Client Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: | 
          echo "Building Client Docker image..."
          docker build -t $CLIENT_REPOSITORY:$IMAGE_TAG ./client

          echo "Tagging Client Docker image..."
          docker tag $CLIENT_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$CLIENT_REPOSITORY:$IMAGE_TAG

          echo "Pushing Client Docker image..."
          docker push $ECR_REGISTRY/$CLIENT_REPOSITORY:$IMAGE_TAG

      # Step 5: Build and Push Server Image
      - name: Build and Push Server Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: | 
          echo "Building Server Docker image..."
          docker build -t $SERVER_REPOSITORY:$IMAGE_TAG ./server

          echo "Tagging Server Docker image..."
          docker tag $SERVER_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$SERVER_REPOSITORY:$IMAGE_TAG

          echo "Pushing Server Docker image..."
          docker push $ECR_REGISTRY/$SERVER_REPOSITORY:$IMAGE_TAG
