name: Deploy to Amazon Public ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1  # Public ECR is only in us-east-1
  ECR_REGISTRY: public.ecr.aws/m7y5i5k9
  REPOSITORY_NAME: employeeapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials (Required for Public ECR push)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
          aws-region: us-east-1  # Public ECR is always in us-east-1

      # Step 3: Login to Amazon Public ECR
      - name: Login to Amazon Public ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      # Step 4: Build, Tag, and Push Client Image
      - name: Build, Tag, and Push Client Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building Client Docker image..."
          docker build -t $REPOSITORY_NAME:client-$IMAGE_TAG ./client
          echo "Tagging Client Docker image..."
          docker tag $REPOSITORY_NAME:client-$IMAGE_TAG $ECR_REGISTRY/$REPOSITORY_NAME:client-$IMAGE_TAG
          echo "Pushing Client Docker image..."
          docker push $ECR_REGISTRY/$REPOSITORY_NAME:client-$IMAGE_TAG

      # Step 5: Build, Tag, and Push Server Image
      - name: Build, Tag, and Push Server Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building Server Docker image..."
          docker build -t $REPOSITORY_NAME:server-$IMAGE_TAG ./server
          echo "Tagging Server Docker image..."
          docker tag $REPOSITORY_NAME:server-$IMAGE_TAG $ECR_REGISTRY/$REPOSITORY_NAME:server-$IMAGE_TAG
          echo "Pushing Server Docker image..."
          docker push $ECR_REGISTRY/$REPOSITORY_NAME:server-$IMAGE_TAG
